= Welcome to Innovation Day 3

Welcome! This lab is your hands-on introduction 


<content here>

== What You Will Learn in This Lab

By the end of this session, you'll have a practical understanding of:

. *Getting Started with AI in Python:*


.Your Lab Environment Overview
[cols="1,2"]
|===
|Component |Details

|Virtual Environment
|`~/venv`, Python 3.12

|Operating System
|Red Hat Enterprise Linux (RHEL) 9.5, with NVIDIA drivers and CUDA toolkit installed. (CUDA is a parallel computing platform and programming model developed by NVIDIA for general computing on its own GPUs.)

|GPU
|NVIDIA L4 (24GB VRAM)

|LLM Runtime (Development)
|Ollama 
(In production, you would typically use Red Hat OpenShift AI with a runtime like `vLLM`.)
|===

[TIP]
====
You can monitor your GPU's utilization at any time by typing the `nvtop` command in a terminal. 

Your lab interface provides two terminals in the "Terminal Tab," but you can open additional terminals as needed directly within the JupyterLab interface.

====


[NOTE]
====
This lab runs in JupyterLab, an interactive development environment you'll access directly through your web browser. Think of JupyterLab as a workbench that's excellent for hands-on experimentation, which is especially useful in AI development.

Within JupyterLab, we'll be using Jupyter Notebooks. A Notebook is like an interactive document where you can:

* Write and execute Python code in small, manageable cells.
* Instantly see the output from your code.
* Easily modify code and vars and re-execute 
* Combine code with explanatory text (like this!), images, and charts, all in one place.
This combination makes Notebooks ideal for learning new concepts and testing ideas step-by-step.

.Quick interactive introduction to using and customizing Jupyter Lab (recommended)
++++
<iframe 
  src="https://demo.arcade.software/eF1CtDuuD4hKWspBmiYR?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true"
  width="100%" 
  height="600px" 
  frameborder="0" 
  allowfullscreen
  webkitallowfullscreen
  mozallowfullscreen
  allow="clipboard-write"
  muted>
</iframe>
++++

====

