= Welcome to Q3 2025 Innovation Day

This lab is a hands-on introduction to Retrieval Augmented Generation (RAG) in Python.

RAG is a technique for enhancing the accuracy and reliability of generative AI models with facts fetched from external sources of knowledge to supplement the LLM’s internal representation of information.

In this lab you will learn about LangChain, a framework for simplifying the development of AI applications by providing a standard way to chain together language models with external data sources and other components and tools. 

As you go through, you will also learn a little about how RAG works and the concepts behind it. 

The steps are:

1. Install dependencies
2. Quick LangChain tutorial (optional)
3. Download and transform data
4. Generate embeddings and add to the Vector Store
5. Build the RAG chain
6. Query and test the RAG system

== Getting Started

Open the Jupyter Notebook `cloud-version-rag-lab-with-langchain.ipynb` in the JupyterLab interface by double clicking on it.
The Jupyter Notebook will guide you through all the steps of building a RAG system using LangChain.

[NOTE]
====
This lab runs in JupyterLab, an interactive development environment you'll access directly through your web browser. Think of JupyterLab as a workbench that's excellent for hands-on experimentation, which is especially useful in AI development.

Within JupyterLab, we'll be using Jupyter Notebooks. A Notebook is like an interactive document where you can:

* Write and execute Python code in small, manageable cells.
* Instantly see the output from your code.
* Easily modify code and vars and re-execute 
* Combine code with explanatory text (like this!), images, and charts, all in one place.
This combination makes Notebooks ideal for learning new concepts and testing ideas step-by-step.

.Quick interactive introduction to using and customizing Jupyter Lab (recommended)
++++
<iframe 
  src="https://demo.arcade.software/eF1CtDuuD4hKWspBmiYR?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true"
  width="100%" 
  height="600px" 
  frameborder="0" 
  allowfullscreen
  webkitallowfullscreen
  mozallowfullscreen
  allow="clipboard-write"
  muted>
</iframe>
++++

====

[TIP]
====
You can monitor your GPU's utilization at any time by typing the `nvtop` command in a terminal. 

Your lab interface provides two terminals in the "Terminal Tab," but you can open additional terminals as needed directly within the JupyterLab interface.

====
